### ISSUE TITLE
Inconsistency: 0 max when only negative values are displayed

### ISSUE THREAD

**Issue by Ashfaak** [hotNipi/node-red-contrib-ui-value-trail#1]
When all values are positive, 0 is not min, which seems preferable:
![image](https://user-images.githubusercontent.com/10670395/81900966-1d880600-95be-11ea-908d-5b722a930089.png)

When all values are negative, 0 is max:
![image](https://user-images.githubusercontent.com/10670395/81901074-3f818880-95be-11ea-9869-021841a2b86d.png)

**Comment by hotNipi** [comment]
Thank you for reporting,
Fixed in v0.1.6

**Comment by Ashfaak** [comment]
Tested, works. Thank you very much. 

![image](https://user-images.githubusercontent.com/10670395/81934393-2f35d180-95ef-11ea-80ad-6af014a5de8b.png)
