### ISSUE TITLE
display issues

### ISSUE THREAD

**Issue by egs2003** [hotNipi/node-red-contrib-ui-value-trail#3]
the diagram is not displayed when navigating to the page with the diagram in dashboard. The page must always be refreshed. I use the Chrome browser und version node-red-contrib-ui-value-trail 0.2.1 of your widget

**Comment by hotNipi** [comment]
Can't reproduce. Chrome, Edge (the new one), Firefox tested. No issues.
You can may be go deeper in steps how to reproduce.

**Comment by egs2003** [comment]
here is a screen capture of the failure
https://www.dropbox.com/t/dwMCDWB8k6c9loT6

**Comment by hotNipi** [comment]
Maybe something went wrong, the video does not play anything, (kind of small also 1450kb)

But I think I can improve the initialization phase, even if I cant reproduce it.
I have done it for other widgets, it may be same reason here. Ill try to fix it within weekend if possible.

**Comment by egs2003** [comment]
try the video with vlc player

**Comment by hotNipi** [comment]
Version 0.2.2 published with improved initial phase

**Comment by egs2003** [comment]
0.2.2 works, thx

**Comment by hotNipi** [comment]
Thanks for reporting.
