### ISSUE TITLE
formatting

### ISSUE THREAD

**Issue by egs2003** [hotNipi/node-red-contrib-ui-value-trail#4]
The display cannot be formatted as clearly as shown in the GitHub readme. For me, the value is always on the diagram. This makes it hard to see the value sometimes. I would also like to display the diagram below the value or to the right of the value

**Comment by hotNipi** [comment]
The github image is not made with value-trail showing the value. The value is shown with regular text widget and the value trail is placed independently and configured to not show the value.

**Comment by egs2003** [comment]
Ok, thx
